scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: bottom_lidar_scan_link
    min_x: -0.1
    max_x: 0.7
    min_y: -0.25
    max_y: 0.25
    min_z: -1.0
    max_z: 1.0