scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: bottom_lidar_link
    min_x: -2.0
    max_x: 2.0
    min_y: -2.0
    max_y: 2.0
    min_z: -1.0
    max_z: 1.0