# always_send_full_costmap: true

# footprint: [ [2.53, 0.625], [-0.82, 0.625], [-0.82, -0.625], [2.53, -0.625] ]
# footprint_padding: 0.1
# obstacle_range: 10.0
# raytrace_range: 8.5
robot_radius: 0.17


static_layer:
  # unknown_cost_value: -1
  # lethal_cost_threshold: 100
  # first_map_only: false
  # subscribe_to_updates: true
  # track_unknown_space: true
  # use_maximum: true
  # trinary_costmap: true
  # marking: false
  # clearing: true
  map_topic: /map
  subscribe_to_updates: false


inflation_layer:
  cost_scaling_factor: 4.0 # 0.5 the bigger the steeper the gradient is
  inflation_radius: 0.1 # the bigger the better, defines where the gradient is

laser_obstacle_layer:
    # footprint_clearing_enabled: true
    # combination_method: 1  # 0 - overwrite, 1 - max, 99 - nothing
    # inflation_radius: 0.2 #added !
    # track_unknown_space: true #try to false

    observation_sources: laser_scan
    laser_scan:
        sensor_frame: bottom_ydlidar_scan_link
        data_type: LaserScan
        topic: /bottom_ydlidar_scan/filtered
        marking: true
        clearing: true
        obstacle_range: 9.0
        raytrace_range: 10.0
        expected_update_rate: 2
        # inf_is_valid: true


  # laser_obstacle_layer:
  #   enabled:              true
  #   max_obstacle_height:  0.6
  #   origin_z:             0.0
  #   z_resolution:         0.2
  #   z_voxels:             2
  #   unknown_threshold:    20
  #   mark_threshold:       0
  #   combination_method:   1
  #   track_unknown_space:  false    #true needed for disabling global path planning through unknown space
  #   obstacle_range: 2.5
  #   raytrace_range: 3.0
  #   origin_z: 0.0
  #   z_resolution: 0.2
  #   z_voxels: 2
  #   publish_voxel_map: false
  #   observation_sources:  laser_scan_sensor
  #   laser_scan_sensor:
  #     data_type: LaserScan
  #     topic: bottom_ydlidar_scan/filtered
  #     marking: true
  #     clearing: true