global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 0.5
  # always_send_full_costmap: true
  static_map: true  #added!

  transform_tolerance: 1.0
  resolution: 0.1

  width: 30.0
  height: 30.0

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
