
#Configuation for robot odometry EKF
#
frequency: 30
sensor_timeout: 0.1

# two_d_mode: true
two_d_mode: false # FOR TEST

publish_tf: true
# initial_state: [5.0,  4.0,  3.0,
#                0.0,  0.0,  1.57,
#                 0.1,  0.2,  0.3,
#                 0.0,  0.0,  0.0,
#                 0.0,  0.0,  0.0]

# Complete the frames section
map_frame: map
odom_frame: odom
base_link_frame: rs_camera_link
# base_link_frame: base_footprint
world_frame: odom
transform_time_offset: 0.0
use_control: false

# The values are ordered as 
#     x, y, z, 
#     roll, pitch, yaw, 
#     vx, vy, vz, 
#     vroll, vpitch, vyaw, 
#     ax, ay, az

# Stereo visual odometry
odom0: /kitty/vo
odom0_config:
  [ true,   true,   true,
    true,   true,   true,
    true,   true,   true,
    true,  true,  true,
    true,  true,  true]
odom0_relative: true
odom0_pose_rejection_threshold: 10000000 # Mahalanobis distance
odom0_twist_rejection_threshold: 10000000
# odom0_queue_size: 5

# RS IMU 
imu0: /rs_camera/imu/filtered
imu0_config:
  [ false,   false,   false,
    true,   true,   true,
    true,   true,   true,
    true,  true,  true,
    true,  true,  true]
imu0_differential: true
imu0_relative: false
imu0_remove_gravitational_acceleration: true
# imu0_queue_size: 50


# Wheel odometry
# odom1: /tigra/wheel_odom
# odom1_config:
#   [ false,  false,  false,
#     false,  false,  false,
#     true,   false,  false,
#     false,  false,  false,
#     false,  false,  false]
# odom1_queue_size: 5
# odom1_differential: true
# odom1_relative: false


# process_noise_covariance: [0.005, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0.005, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0.006, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0.003, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0.003, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0.006, 0,     0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0.0025, 0,     0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0.0025, 0,    0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0.004, 0,    0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0.001, 0,    0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.001, 0,    0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.002, 0,    0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.001, 0,    0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.001, 0,
#                            0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.0015]


# initial_estimate_covariance: [7.11*1e-8, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                               0,    7.11*1e-8, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                               0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                               0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                               0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                               0,    0,    0,    0,    0,    2.77*1e-8, 0,    0,    0,    0,     0,     0,     0,    0,    0,
#                               0,    0,    0,    0,    0,    0,    0.071, 0,    0,    0,     0,     0,     0,    0,    0,
#                               0,    0,    0,    0,    0,    0,    0,    0.071, 0,    0,     0,     0,     0,    0,    0,
#                               0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
#                               0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
#                               0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
#                               0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e5,  0,    0,    0,
#                               0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0.028, 0,    0,
#                               0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
#                               0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]